package bo.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/** Represents one chat message with a speaker label and message text. */
public final class DialogBox extends HBox {
    /** The speaker label injected from the FXML view. */
    @FXML
    private Label speaker;

    /** The message label injected from the FXML view. */
    @FXML
    private Label dialog;

    /** The private constructor used by the named factory methods. */
    private DialogBox(String message, String speakerName) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setRoot(this);
            fxmlLoader.setController(this);
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load a Bo dialog box.", exception);
        }

        speaker.setText(speakerName);
        dialog.setText(message);
    }

    /**
     * Creates a right-aligned dialog for user input.
     *
     * @param message the command entered by the user.
     * @return a user dialog box.
     */
    public static DialogBox getUserDialog(String message) {
        return new DialogBox(message, "You");
    }

    /**
     * Creates a left-aligned dialog for a Bo response.
     *
     * @param message the response generated by Bo.
     * @return a Bo dialog box.
     */
    public static DialogBox getBoDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "Bo");
        dialogBox.flip();
        return dialogBox;
    }

    /** Places the speaker label on the left side of the dialog. */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
    }
}
